# -*- coding: utf-8 -*-
"""2. Finalizing Study Areas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VVLWAb5_6DHsCRMdU_0KRipRe7P_jiZP

# Urban Informatics Final Project: Cleaned Data for Final Study Areas

Spring 2026

**Contributors:** Anwar Baroudi, Phoebe Chiu, Noelani Fixler, Michael Huang
"""

# Import packages
import pandas as pd
import geopandas as gpd

# Import raw and intermediary processed data from Github
mtc_epcs = gpd.read_file('https://github.com/AnwarBaroudi/MAPN/raw/main/data/raw/equity_priority_communities_2020_acs2018.zip')
proj_schools_public_gdf = gpd.read_file('https://github.com/AnwarBaroudi/MAPN/raw/main/data/processed/proj_schools_public.geojson')
bus = pd.read_csv('https://github.com/AnwarBaroudi/MAPN/raw/main/data/raw/actransit_gtfs.csv')

# Filter the `mtc_epcs` dataframe for Alameda County EPCs only
mtc_ac_epcs = mtc_epcs[mtc_epcs['county_fip'] == '001']

# Create a geodataframe from the AC Transit GTFS data
bus_gdf = gpd.GeoDataFrame(
    bus,
    geometry=gpd.points_from_xy(bus['stop_lon'], bus['stop_lat'],
    crs = 4326)
    )

# Create an array of school types
school_types = proj_schools_public_gdf['SchoolType'].unique()

# Create a list of school types
school_types_list = school_types.tolist()

# Create a for loop to create the binary variables
for v in school_types:
    proj_schools_public_gdf[f"{v}"] = (proj_schools_public_gdf["SchoolType"] == v).astype(int)

# Create a dataframe with important sites attributes
site_school_info = proj_schools_public_gdf.groupby('geoid').agg(
    SchoolCount=('EnrollTotal', 'size'),
    EnrollTotal=('EnrollTotal', 'sum'),
    SEDTotal=('SEDCount', 'sum'),
    **{col: (col, 'sum') for col in school_types_list},
    tot_pop=('tot_pop', 'first'),
    pct_poc=('pct_poc', 'first'),
    pct_spfam=('pct_spfam', 'first'),
    pct_lep=('pct_lep', 'first'),
    pct_below2=('pct_below2', 'first'),
    pct_zvhhs=('pct_zvhhs', 'first')
).reset_index()

# Create a variable with the percentage of students
site_school_info['pct_students'] = site_school_info['EnrollTotal'] / site_school_info['tot_pop']

# Create a variable with the percentage of SED students
site_school_info['sed_share'] = site_school_info['SEDTotal'] / site_school_info['EnrollTotal']

# Create a variable with average school size
site_school_info['avg_school_size'] = site_school_info['EnrollTotal'] / site_school_info['SchoolCount']

# Conduct a spatial join of the bus stops with the epcs
proj_bus_stops_gdf = gpd.sjoin(bus_gdf, mtc_ac_epcs, how='inner', predicate='within')

# Create a dataframe with number of bus stops per Alameda County EPC
site_bus_info = proj_bus_stops_gdf.groupby('geoid').agg(
    StopCount=('stop_code', 'size')
).reset_index()

# Add the bus stop data to `potential_public_sites`
potential_public_sites = pd.merge(mtc_ac_epcs, site_bus_info, on='geoid', how='inner')

# Add the school data to `potential_public_sites`
potential_public_sites = pd.merge(potential_public_sites, site_school_info, on='geoid', how='left')

# Drop all columns ending with '_y'
potential_public_sites = potential_public_sites.loc[
    :, ~potential_public_sites.columns.str.endswith('_y')
]

# Rename columns to remove '_x'
potential_public_sites.columns = (
    potential_public_sites.columns.str.replace('_x$', '', regex=True)
)

# Create a column for bus stops per 1000 students
potential_public_sites['bus_stop_per_cap'] = potential_public_sites['StopCount'] / potential_public_sites['EnrollTotal'] * 1000

# Only keep EPCs with one of the following schools
filtered_public_sites = potential_public_sites[
    (potential_public_sites['K-12'] > 0) |
    (potential_public_sites['High'] > 0) |
    (potential_public_sites['Middle'] > 0)]

# Run summary statistics
filtered_public_sites[['SchoolCount', 'EnrollTotal', 'SEDTotal',
                        'K-12', 'High','Middle',
                        'pct_zvhhs', 'pct_students', 'sed_share',	'avg_school_size', 'bus_stop_per_cap']].describe()

# Apply filters for filtered dataframe
final_sites_1 = filtered_public_sites[
    (filtered_public_sites['pct_students'] > 0.25) &
    (filtered_public_sites['pct_zvhhs'] > 0.15)][['geoid', 'SchoolCount', 'EnrollTotal', 'SEDTotal',
                        'K-12', 'High','Middle',
                        'pct_zvhhs', 'pct_students', 'sed_share',	'avg_school_size', 'bus_stop_per_cap']]

# Apply filters for filtered dataframe
final_sites_2 = filtered_public_sites[
    (filtered_public_sites['bus_stop_per_cap'] < 12) &
    (filtered_public_sites['pct_zvhhs'] > 0.15)][['geoid','SchoolCount', 'EnrollTotal', 'SEDTotal',
                        'K-12', 'High','Middle',
                        'pct_zvhhs', 'pct_students', 'sed_share',	'avg_school_size', 'bus_stop_per_cap']]

# Get final_sites
final_sites = pd.concat([final_sites_1, final_sites_2])

# Create a list
final_sites = final_sites['geoid'].unique().tolist()

# Update final_sites as a dataframe
final_sites = filtered_public_sites[filtered_public_sites['geoid'].isin(final_sites)]

# Explore the project dataframe of schools
m = proj_schools_public_gdf.explore(color="blue", name="Schools")

final_sites.explore(
    m=m,
    color="red",
    name="Study Areas"
)
m

# Finalize sites
final_sites = final_sites[
    (final_sites['geoid'] == '06001402500') | # West Oakland
    (final_sites['geoid'] == '06001406000') | # Nimitz
    (final_sites['geoid'] == '06001408800') # Airport
     ]

# Create a dataframe for each individual EPC
wo_epc_gdf = final_sites[final_sites['tract'] == 402500]
nimitz_epc_gdf = final_sites[final_sites['tract'] == 406000]
oak_airport_epc_gdf = final_sites[final_sites['tract'] == 408800]

# Get a truncated dataframe
final_sites[['geoid', 'tot_pop', 'pct_zvhhs',  'epc_class', 'StopCount',
       'SchoolCount', 'EnrollTotal', 'SEDTotal', 'K-12', 'Elementary',
     'High', 'Middle',
       'Continuation', 'pct_students', 'sed_share',
       'avg_school_size', 'bus_stop_per_cap']].T

# Correct the variable type of the `tract` column of the sschools dataframe
proj_schools_public_gdf['geoid'] = proj_schools_public_gdf['geoid'].astype(float).astype(int)

# Filter the schools dataframe to only include our EPCs of interest
final_schools_gdf = proj_schools_public_gdf[
    (proj_schools_public_gdf['geoid'] == 6001402500) | # West Oakland
    (proj_schools_public_gdf['geoid'] == 6001406000) | # Nimitz
    (proj_schools_public_gdf['geoid'] == 6001408800) # Airport
]

# Drop elementary schools in the final schools dataframe
final_schools_gdf = final_schools_gdf[final_schools_gdf['GradeHigh'] != '05']

# Create individual dataframes for the schools
wo_epc_schools = final_schools_gdf[final_schools_gdf['geoid'] == 6001402500]
nimitz_epc_schools = final_schools_gdf[final_schools_gdf['geoid'] == 6001406000]
oak_airport_epc_schools = final_schools_gdf[final_schools_gdf['geoid'] == 6001408800]

# Create the final bus stops
final_bus_stops_gdf = gpd.sjoin(bus_gdf, final_sites, how='inner', predicate='within')

# Create individual dataframes for the bus stops
wo_bus_stops = final_bus_stops_gdf[final_bus_stops_gdf['geoid'] == '06001402500']
nimitz_bus_stops = final_bus_stops_gdf[final_bus_stops_gdf['geoid'] == '06001406000']
oak_bus_stops = final_bus_stops_gdf[final_bus_stops_gdf['geoid'] == '06001408800']

# Explore final dataframes in a map

m = final_sites.explore(
    color="red",
    style_kwds={
        "fillOpacity": 0.1,
        "weight": 1
    },
    tooltip=[
        'geoid', 'SchoolCount', 'EnrollTotal', 'SEDTotal',
        'K-12', 'High', 'Middle',
        'pct_zvhhs', 'pct_students', 'sed_share',
        'avg_school_size', 'bus_stop_per_cap'
    ],
    highlight=False,
    tiles="CartoDB positron",
    name="Study Areas"
)

# Schools on top
m = final_schools_gdf.explore(
    m=m,
    color="blue",
    name="Schools",
    tooltip=["SchoolName"],
    popup=True
)

# Bus stops on top
m = final_bus_stops_gdf.explore(
    m=m,
    color="darkgreen",
    name="Bus Stops",
    tooltip=["stop_name"],
    popup=True
)

m

# Export the cleaned GeoDataFrames
outputs = [
    # Study Areas
    (final_sites, "CP 255 Final Project EPCs.geojson"),
    (wo_epc_gdf, "CP 255 Final Project West Oakland EPC.geojson"),
    (nimitz_epc_gdf, "CP 255 Final Project Nimitz EPC.geojson"),
    (oak_airport_epc_gdf, "CP 255 Final Project Oak Airport EPC.geojson"),

    # Schools
    (final_schools_gdf, "CP 255 Final Project Schools.geojson"),
    (wo_epc_schools, "CP 255 Final Project West Oakland Schools.geojson"),
    (nimitz_epc_schools, "CP 255 Final Project Nimitz Schools.geojson"),
    (oak_airport_epc_schools, "CP 255 Final Project Oak Airport Schools.geojson"),

    # Bus Stops
    (final_bus_stops_gdf, "CP 255 Final Project Bus Stops.geojson"),
    (wo_bus_stops, "CP 255 Final Project West Oakland Bus Stops.geojson"),
    (nimitz_bus_stops, "CP 255 Final Project Nimitz Bus Stops.geojson"),
    (oak_bus_stops, "CP 255 Final Project Oak Airport Bus Stops.geojson"),
]

for gdf, filename in outputs:
    gdf.to_file(filename, driver="GeoJSON")
