# -*- coding: utf-8 -*-
"""5_Network Graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BPlNHgHm_A1oG04M-8xti6JRKTtUe3a2

# Urban Informatics Final Project: Tile2Net to Network Graphs

Spring 2026

**Contributors:** Anwar Baroudi, Phoebe Chiu, Noelani Fixler, Michael Huang

## **1. Set Up Document**
"""

!curl -s -o pyproject.toml https://raw.githubusercontent.com/gboeing/osmnx-workshop/refs/heads/main/pyproject.toml && uv pip install -r pyproject.toml
!pip install contextily

# !pip install networkx==2.8.8

# Import packages
# from IPython.display import display
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
from shapely.geometry import box
import networkx as nx
import osmnx as ox
import folium
import contextily as ctx
import math
from shapely.geometry import Point, LineString

# configure OSMnx
ox.settings.log_console = True
print(ox.__version__)

# Import cleaned tile2net GeoJSON files from MAP'N Github
# t2n_nimitz = gpd.read_file("https://github.com/AnwarBaroudi/MAPN/raw/main/data/processed/t2n_nimitz_cleaned.geojson")
# t2n_airport = gpd.read_file("https://github.com/AnwarBaroudi/MAPN/raw/main/data/processed/t2n_oak_airport_cleaned.geojson")
# t2n_wo = gpd.read_file("https://github.com/AnwarBaroudi/MAPN/raw/main/data/processed/t2n_west_oakland_cleaned.geojson")

# # Set CRS to EPSG:4326
# t2n_nimitz = t2n_nimitz.to_crs(epsg=4326)
# t2n_airport = t2n_airport.to_crs(epsg=4326)
# t2n_wo = t2n_wo.to_crs(epsg=4326)

# # Set CRS to EPSG:3857
# t2n_nimitz = t2n_nimitz.to_crs(epsg=3857)
# t2n_airport = t2n_airport.to_crs(epsg=3857)
# t2n_wo = t2n_wo.to_crs(epsg=3857)

# get the ones with phantom edges
t2n_nimitz_p = gpd.read_file("https://github.com/MiAnPh/MAPN-SRTS/raw/main/data/processed/t2n_nimitz_phantom.geojson")
t2n_airport_p = gpd.read_file("https://github.com/MiAnPh/MAPN-SRTS/raw/main/data/processed/t2n_oak_airport_phantom.geojson")
t2n_wo_p = gpd.read_file("https://github.com/MiAnPh/MAPN-SRTS/raw/main/data/processed/t2n_west_oakland_phantom.geojson")

# Set CRS to EPSG:4326
t2n_nimitz_p = t2n_nimitz_p.to_crs(epsg=4326)
t2n_airport_p = t2n_airport_p.to_crs(epsg=4326)
t2n_wo_p = t2n_wo_p.to_crs(epsg=4326)

# Print unique field types of all t2n gdfs
# print("Nimitz", "/n", t2n_nimitz_p['f_type'].unique(), "\n")
# print("Airport", "/n", t2n_airport_p['f_type'].unique(), "\n")
# print("West Oakland", "/n", t2n_wo_p['f_type'].unique(), "\n")

# Replace variables
# t2n_nimitz["f_type"] = t2n_nimitz["f_type"].replace({
#     "sidewalk_plussidewalk_plus": "sidewalk_plus"
# })
t2n_nimitz_p["f_type"] = t2n_nimitz_p["f_type"].replace({
    "sidewalk_plussidewalk_plus": "sidewalk_plus"
})

# t2n_airport["f_type"] = t2n_airport["f_type"].replace({
#     "sidewalk_+": "sidewalk_plus",
#     "crosswalk_+": "crosswalk_plus",
#     "crossing_+": "crosswalk_plus",
#     "curb_+": "sidewalk_plus",
#     "bus_island_+": "sidewalk_plus",
#     "sidewalk_connection_+": "sidewalk_connection_plus"
# })
t2n_airport_p["f_type"] = t2n_airport_p["f_type"].replace({
    "sidewalk_+": "sidewalk_plus",
    "crosswalk_+": "crosswalk_plus",
    "crossing_+": "crosswalk_plus",
    "curb_+": "sidewalk_plus",
    "bus_island_+": "sidewalk_plus",
    "sidewalk_connection_+": "sidewalk_connection_plus",
    "pahntom_sidewalk": "phantom_sidewalk",
})

# t2n_wo["f_type"] = t2n_wo["f_type"].replace({
#     "sidwalk": "sidewalk"
# })
t2n_wo_p["f_type"] = t2n_wo_p["f_type"].replace({
    "sidwalk": "sidewalk"
})

t2n_nimitz = t2n_nimitz_p.loc[(~t2n_nimitz_p['f_type'].str.contains('phantom'))]
t2n_airport = t2n_airport_p.loc[(~t2n_airport_p['f_type'].str.contains('phantom'))]
t2n_wo = t2n_wo_p.loc[(~t2n_wo_p['f_type'].str.contains('phantom'))]

t2n_nimitz_only_p = t2n_nimitz_p.loc[(t2n_nimitz_p['f_type'].str.contains('phantom'))]
t2n_airport_only_p = t2n_airport_p.loc[(t2n_airport_p['f_type'].str.contains('phantom'))]
t2n_wo_only_p = t2n_wo_p.loc[(t2n_wo_p['f_type'].str.contains('phantom'))]

print("Nimitz: ", t2n_nimitz['f_type'].unique(), "\n")
print("Airport: ", t2n_airport['f_type'].unique(), "\n")
print("West Oakland: ", t2n_wo['f_type'].unique(), "\n")



# Query AC Transit data
ac_transit_stops_url = "https://services2.arcgis.com/AVso4yDITKsybTJg/arcgis/rest/services/AC_Transit_Bus_Stops/FeatureServer/0/query?where=1=1&outFields=*&f=geojson"
ac_transit_stops = gpd.read_file(ac_transit_stops_url)

# Query the Oakland ArcGIS server

# 2024 HIN Pedestrian data
hin_url = "https://services.arcgis.com/9tC74aDHuml0x5Yz/arcgis/rest/services/HIN_2024_Final_gdb/FeatureServer/3/query?where=1=1&outFields=*&f=geojson"
oak_hin_ped = gpd.read_file(hin_url)

# Speed Limits
speed_limits_url = (
    "https://services.arcgis.com/9tC74aDHuml0x5Yz/ArcGIS/rest/services/"
    "Oakland_Speed_Limits__ADT__and_85th_Percentile_Speeds_WFL1/FeatureServer/1/query"
    "?where=1%3D1"
    "&outFields=*"
    "&returnGeometry=true"
    "&outSR=4326"
    "&f=geojson"
)
oak_speed_limits = gpd.read_file(speed_limits_url)
oak_speed_limits.crs



#speed limit function
def get_speed_limit(line, speed_limit_df):
  geo_line = gpd.GeoDataFrame(geometry=[line], crs='4326')
  join_df = gpd.sjoin(geo_line, speed_limit_df, how="inner")
  if not join_df.empty:
    speed_limit = join_df.iloc[0]['OMC_SPD']
    return speed_limit
  else:return 25

cross_walk_df = t2n_wo.loc[t2n_wo['f_type'] == 'crosswalk']

line = cross_walk_df.iloc[3].geometry
oak_speed_limits_buffered = oak_speed_limits.copy()
oak_speed_limits_buffered['geometry'] = oak_speed_limits['geometry'].buffer(.0005)

get_speed_limit(line, oak_speed_limits_buffered)
#function works

#finding crosswalks with speed limits
nimitz_crosswalks = t2n_nimitz[t2n_nimitz['f_type'] == 'crosswalk']

m = nimitz_crosswalks.explore(
    color="orange",
    style_kwds={
        "fillOpacity": 0.1,
        "weight": 2
    },
    tooltip=True,
    popup=True,
    tiles="CartoDB positron",
    name="Nimitz Crosswalks"
)

m

# Apply the get_speed_limit function to each crosswalk in nimitz_crosswalks
nimitz_crosswalks['speed_limit'] = nimitz_crosswalks.geometry.apply(lambda x: get_speed_limit(x, oak_speed_limits_buffered))

# Display the crosswalks with their new speed_limit column
display(nimitz_crosswalks[['f_type', 'speed_limit', 'geometry']].head())

"""## **2. Analyze OSMnx Street Network**

### *a. Generate OSMnx Street Graphs*
"""

# Create a dictionary of the t2n files
t2n_files = {
    "West Oakland": t2n_wo,
    "Airport": t2n_airport,
    "Nimitz": t2n_nimitz
}
t2n_p_files = {
    "West Oakland": t2n_wo_p,
    "Airport": t2n_airport_p,
    "Nimitz": t2n_nimitz_p
}

# Create a function to create a dictionary of networkx graphs using a bounding box
# The bounding box is based on the t2n file boundaries

def create_street_graph(gdf, name):

    # Compute Bounding Box
    minx, miny, maxx, maxy = gdf.total_bounds
    bbox = box(minx, miny, maxx, maxy)

    # Create street network graph
    G = ox.graph_from_polygon(
        bbox,
        network_type="drive"
    )

    # Store the name of the graph
    G.graph["name"] = name

    return G

def organize_street_graphs(gdf_dict):

    # Create the graphs dictionary
    graphs = {}

    # Loop through input dictionary
    for name, gdf in gdf_dict.items():
        graphs[name] = create_street_graph(gdf, name)

    return graphs

# Create the dictionary of nx graphs
street_graphs = organize_street_graphs(t2n_files)

# Plot street nx graphs
for name, G in street_graphs.items():
    fig, ax = ox.plot_graph(G, show=False, close=False)
    ax.set_title(name)
    plt.show()
    plt.close(fig)

# Create separate graphs from street_graphs
wo_street_graph, oak_street_graph, nimitz_street_graph = street_graphs.values()

wo2 = wo_street_graph.copy()
# wo2['weight'] = wo2['length']
for u,v,w in wo2.edges:
    wo2.edges[u,v,w]['weight'] = wo2.edges[u,v,w]['length']
# x,y,z = 558572420, 558572426, 0
# print(wo2.edges[x,y,z])
# gpd.GeoDataFrame(geometry=[wo2.edges[x,y,z]['geometry']],crs=4326).to_crs('3857').iloc[0].geometry.length
# wo2.edges

"""### *b. Plot OSMnx Graphs on Interactive Map*"""

def plot_interactive_maps(graph_dict):

    maps = {}

    for name, G in graph_dict.items():

        # Convert the network graph into a GeoDataFrame
        nodes, edges = ox.graph_to_gdfs(G)

        # Set the CRS
        nodes = nodes.to_crs(epsg=4326)
        edges = edges.to_crs(epsg=4326)

        # Center the map
        center = [
            nodes.geometry.y.mean(),
            nodes.geometry.x.mean()
        ]

        # Use folium to create the map
        m = folium.Map(location=center, zoom_start=13, tiles="CartoDB positron")

        # Set the edges in folium
        folium.GeoJson(
            edges,
            style_function=lambda x: {
                "color": "#5DADE2",
                "weight": 2,
                "opacity": 0.6
            },
            name="Road Network"
        ).add_to(m)

        # Use a for loop to map the nodes
        for _, row in nodes.iterrows():
            folium.CircleMarker(
                location=[row.geometry.y, row.geometry.x],
                radius=1.5,
                color="black",
                fill=True,
                fill_opacity=0.7
            ).add_to(m)

        folium.LayerControl().add_to(m)

        maps[name] = m

    return maps

# Create a dictionary of interactive maps
street_interactive_maps = plot_interactive_maps(street_graphs)

# Create interactive maps
for name, m in street_interactive_maps.items():
    print(f"Displaying: {name}")
    display(m)

"""## **3. Analyze T2N NX Graphs**

### *a. Create T2N Graphs*
"""

def gdf_to_graph(edges_gdf):

    G = nx.MultiDiGraph()

    node_id_map = {}
    node_counter = 0

    def get_node_id(coord):

        nonlocal node_counter

        if coord not in node_id_map:
            node_id_map[coord] = node_counter
            G.add_node(
                node_counter,
                x=coord[0],
                y=coord[1]
            )
            node_counter += 1

        return node_id_map[coord]

    for _, row in edges_gdf.iterrows():

        geom = row.geometry

        if geom is None or geom.is_empty:
            continue

        if geom.geom_type == "LineString":
            lines = [geom]
        elif geom.geom_type == "MultiLineString":
            lines = list(geom.geoms)
        else:
            continue

        attr = row.drop("geometry").to_dict()
        attr = {
            k: str(v) if isinstance(v, (list, dict)) else v
            for k, v in attr.items()
        }
        attr['length'] = geom.length

        for line in lines:

            coords = list(line.coords)
            if len(coords) < 2:
                continue

            u = get_node_id(coords[0])
            v = get_node_id(coords[-1])

            G.add_edge(u, v, **attr)
            G.add_edge(v, u, **attr)

    G.graph["crs"] = "EPSG:4326"
    G.graph["simplified"] = True

    return G


def organize_manual_graphs(gdf_dict):
    # Create the graphs dictionary
    graphs = {}

    for name, gdf in gdf_dict.items():
        graphs[name] = gdf_to_graph(gdf)

    return graphs

# Create t2n_graphs
t2n_graphs = organize_manual_graphs(t2n_files)
t2n_p_graphs = organize_manual_graphs(t2n_p_files)

t2n_graphs

# Create a dictionary of interactive maps
t2n_interactive_maps = plot_interactive_maps(t2n_graphs)

# Create interactive maps
for name, m in t2n_interactive_maps.items():
    print(f"Displaying: {name}")
    display(m)

"""### *b. T2N Graph Weights*"""

# Add weights based on f_types and speed limit

def weight_edges(graph, speed_limit_df):
    graph = ox.distance.add_edge_lengths(graph)

    for u, v, _, data in graph.edges(keys=True, data=True):

        # Set facility type weight variable
        data["f_type_w"] = None

        f_type = data.get("f_type")

        # Assign facility type weights
        if f_type in [
            "sidewalk_plus",
            "sidewalk",
            "sidewalk_connection",
            "sidewalk_connection_plus",
            "phantom_sidewalk"
        ]:
            data["f_type_w"] = 1

        elif f_type in [
            "crosswalk",
            "crosswalk_plus",
            "phantom_crosswalk",
        ]:
            u_coords = graph.nodes[u].values()
            v_coords = graph.nodes[v].values()
            speed_limit = get_speed_limit(LineString([u_coords,v_coords]), speed_limit_df)
            # print(speed_limit)
            data["f_type_w"] = 1.3 + ((speed_limit-25)/50) # Setting the crosswalk weights to 1.3 so it takes 30% longer for crossing
            # print(data["f_type_w"])
        elif f_type in [
            "phantom_midblock",
        ]:
            data["f_type_w"] = 1.05
        data['weight'] = data['length']**data['f_type_w']
    return graph


for key, graph in t2n_graphs.items():
    graph = weight_edges(graph, oak_speed_limits)
    t2n_graphs[key] = graph

# do it again for the phantom graphs
for key, graph in t2n_p_graphs.items():
    graph = weight_edges(graph, oak_speed_limits)
    t2n_p_graphs[key] = graph

# Create separate graphs from t2n_graphs
t2n_wo_graph, t2n_oak_graph, t2n_nimitz_graph = t2n_graphs.values()
t2n_wo_graph_p, t2n_oak_graph_p, t2n_nimitz_graph_p = t2n_p_graphs.values()



"""### *c. Run Shortest Path*"""

# Call in data for visualizing the shortest paths
# Gather the final schools, buses, and EPCs
final_epcs_gdf = gpd.read_file("https://github.com/AnwarBaroudi/MAPN/raw/main/data/processed/CP%20255%20Final%20Project%20EPCs.geojson")
final_schools_gdf = gpd.read_file("https://github.com/AnwarBaroudi/MAPN/raw/main/data/processed/CP%20255%20Final%20Project%20Schools.geojson")
final_bus_stops_gdf = gpd.read_file("https://github.com/AnwarBaroudi/MAPN/raw/main/data/processed/CP%20255%20Final%20Project%20Bus%20Stops.geojson")

# Drop a school with duplicate geometry + permanently closed
final_schools_gdf  = final_schools_gdf [final_schools_gdf['SchoolName'] != 'Ralph J. Bunche Continuation High']

# Create ac_final_stops_gdf
# ac_final_stops_gdf = gpd.sjoin(ac_transit_stops, final_epcs_gdf, how='inner', predicate='within')
# ac_final_stops_gdf = ac_final_stops_gdf.drop(columns=["index_right"])


# seperate and clip the schools and stops
final_epcs_gdf = final_epcs_gdf.to_crs('3857')
ac_final_stops_gdf = ac_transit_stops.to_crs('3857')
ac_final_stops_gdf['bus_coords'] = ac_transit_stops.geometry
final_schools_gdf['school_coords'] = final_schools_gdf.geometry
final_schools_gdf = final_schools_gdf.to_crs('3857')

wo_schools_gdf = final_schools_gdf.clip(final_epcs_gdf.iloc[0].geometry)
nm_schools_gdf = final_schools_gdf.clip(final_epcs_gdf.iloc[1].geometry)
oa_schools_gdf = final_schools_gdf.clip(final_epcs_gdf.iloc[2].geometry)

wo_stops_gdf = ac_final_stops_gdf.clip(final_epcs_gdf.iloc[0].geometry)
nm_stops_gdf = ac_final_stops_gdf.clip(final_epcs_gdf.iloc[1].geometry)
oa_stops_gdf = ac_final_stops_gdf.clip(final_epcs_gdf.iloc[2].geometry)

# oa_schools_gdf
# wo_stops_gdf



# edit the stops dataframe with the distances to each school, and get the closest stop to each school per route
def get_distances_to_schools(schools_gdf, input_stops_gdf):

    stops_gdf = input_stops_gdf.copy()
    # Run a for loop on the schools with their locations
    for school_name, school_coords, school_geom in zip(schools_gdf["SchoolName"], schools_gdf["school_coords"], schools_gdf.geometry):

        # Add the column with the school_name that is the distance to that school
        stops_gdf[school_name] = stops_gdf.geometry.distance(school_geom)
        stops_gdf[school_name + "_coords"] = school_coords

    # get individual routes
    routes_dict = {}

    for index, row in stops_gdf.iterrows():

        routes = str(row["ROUTE"]).split()

        for route in routes:
            # Initialize list if route not yet in dictionary
            if route not in routes_dict:
                routes_dict[route] = []

            # Add stop
            routes_dict[route].append(row)

    # make a dictionary from school to its nearest stops for each route
    school2stops = {}

    for school in schools_gdf["SchoolName"]:
        if not school in school2stops:
            school2stops[school] = []

        for k, v in routes_dict.items():
            v = sorted(v, key = lambda row: row[school], reverse = False)
            school2stops[school].append([k, v[0]])

    return school2stops

wo_sts = get_distances_to_schools(wo_schools_gdf,wo_stops_gdf)
nm_sts = get_distances_to_schools(nm_schools_gdf,nm_stops_gdf)
oa_sts = get_distances_to_schools(oa_schools_gdf,oa_stops_gdf)

# get the shortest routes from each bus stop to a given school
def get_shortest_routes(school_name, school2stops, network_graph):
    paths = {}
    rows = school2stops[school_name]
    for route_num, row in rows:
        # approximate start and end point
        bus_x, bus_y = list(row['bus_coords'].coords)[0]
        orig = ox.distance.nearest_nodes(network_graph, bus_x, bus_y)
        school_x, school_y = list(row[school_name + '_coords'].coords)[0]
        dest = ox.distance.nearest_nodes(network_graph, school_x, school_y)
        # calculate route
        path = ox.routing.shortest_path(network_graph, orig, dest, weight="weight")

        paths[route_num] = path

    return paths



wo_routes = get_shortest_routes("West Oakland Middle", wo_sts, t2n_wo_graph)

wo_routes_p = get_shortest_routes("West Oakland Middle", wo_sts, t2n_wo_graph_p)

fig = plt.figure(figsize=[12,12])
ax = fig.add_axes([0, 0, 1, 1])

subgraphs = {k:t2n_wo_graph.subgraph(v) if v else [] for k,v in list(wo_routes.items())}
subgraphs_p = {k:t2n_wo_graph_p.subgraph(v) if v else [] for k,v in wo_routes_p.items()}

wo_schools_gdf.loc[wo_schools_gdf["SchoolName"] == "West Oakland Middle"].plot(ax=ax, color="black", label="school")
wo_stops_gdf.plot(ax=ax, color="orange", label="stops")


t2n_wo_p = t2n_wo_p.to_crs('3857')
t2n_wo_p.plot(ax=ax, color='yellow', label='network')

for k,v in subgraphs_p.items():
    if v:
        _,gdf = ox.convert.graph_to_gdfs(v)
        gdf = gdf.to_crs('3857')
        gdf.plot(ax=ax, color='red', label='after')

for k,v in subgraphs.items():
    if v:
        _,gdf = ox.convert.graph_to_gdfs(v)
        gdf = gdf.to_crs('3857')
        gdf.plot(ax=ax, color='blue', label='before')

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

oa_sts.keys()
# oa_routes

sname = "Coliseum College Prep Academy"

oa_routes = get_shortest_routes(sname, oa_sts, t2n_oak_graph)

oa_routes_p = get_shortest_routes(sname, oa_sts, t2n_oak_graph_p)


fig = plt.figure(figsize=[12,12])
ax = fig.add_axes([0, 0, 1, 1])

subgraphs = {k:t2n_oak_graph.subgraph(v) if v else [] for k,v in list(oa_routes.items())}
subgraphs_p = {k:t2n_oak_graph_p.subgraph(v) if v else [] for k,v in oa_routes_p.items()}

oa_schools_gdf.loc[oa_schools_gdf["SchoolName"] == sname].plot(ax=ax, color="black", label="school")
oa_stops_gdf.plot(ax=ax, color="orange", label="stops")


t2n_airport_p = t2n_airport_p.to_crs('3857')
t2n_airport_p.plot(ax=ax, color='yellow', label='network')

for k,v in subgraphs_p.items():
    if v:
        _,gdf = ox.convert.graph_to_gdfs(v)
        gdf = gdf.to_crs('3857')
        gdf.plot(ax=ax, color='red', label='after')

for k,v in subgraphs.items():
    if v:
        _,gdf = ox.convert.graph_to_gdfs(v)
        gdf = gdf.to_crs('3857')
        gdf.plot(ax=ax, color='blue', label='before')



ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

nm_sts.keys()
# nm_routes_p
# nm_sts

sname = "Downtown Charter Academy"

nm_routes = get_shortest_routes(sname, nm_sts, t2n_nimitz_graph)

nm_routes_p = get_shortest_routes(sname, nm_sts, t2n_nimitz_graph_p)


fig = plt.figure(figsize=[12,12])
ax = fig.add_axes([0, 0, 1, 1])

subgraphs = {k:t2n_nimitz_graph.subgraph(v) if v else [] for k,v in list(nm_routes.items())}
subgraphs_p = {k:t2n_nimitz_graph_p.subgraph(v) if v else [] for k,v in nm_routes_p.items()}

nm_schools_gdf.loc[nm_schools_gdf["SchoolName"] == sname].plot(ax=ax, color="black", label="school")
nm_stops_gdf.plot(ax=ax, color="orange", label="stops")


t2n_nimitz_p = t2n_nimitz_p.to_crs('3857')
t2n_nimitz_p.plot(ax=ax, color='yellow', label='network')

for k,v in subgraphs_p.items():
    if v:
        _,gdf = ox.convert.graph_to_gdfs(v)
        gdf = gdf.to_crs('3857')
        gdf.plot(ax=ax, color='red', label='after')

for k,v in subgraphs.items():
    if v:
        _,gdf = ox.convert.graph_to_gdfs(v)
        gdf = gdf.to_crs('3857')
        gdf.plot(ax=ax, color='blue', label='before')


ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

# find contributing phantom edges

def get_contributing_phantom_edges(sts, graph):
    phantom_edges = set()
    for schoolname in sts.keys():
        routes_p = get_shortest_routes(schoolname, sts, graph)

        for route in routes_p.values():
            if not route:
                continue
            for i in range(1, len(route)):
                if 'phantom' in graph.edges[route[i-1],route[i],0]["f_type"]:
                    phantom_edges.update([route[i-1],route[i]])

    return phantom_edges

wo_pe = get_contributing_phantom_edges(wo_sts, t2n_wo_graph_p)
oa_pe = get_contributing_phantom_edges(oa_sts, t2n_oak_graph_p)
nm_pe = get_contributing_phantom_edges(nm_sts, t2n_nimitz_graph_p)

_, gwo = ox.convert.graph_to_gdfs(t2n_wo_graph_p.subgraph(wo_pe))
gwo = gwo.to_crs('3857')

_, goa = ox.convert.graph_to_gdfs(t2n_oak_graph_p.subgraph(oa_pe))
goa = goa.to_crs('3857')

_, gnm = ox.convert.graph_to_gdfs(t2n_nimitz_graph_p.subgraph(nm_pe))
gnm = gnm.to_crs('3857')

fig = plt.figure(figsize=[12,12])
ax = fig.add_axes([0, 0, 1, 1])

t2n_wo_p = t2n_wo_p.to_crs('3857')
t2n_wo_p.plot(ax=ax, color='orange', label='missing connections')

t2n_wo = t2n_wo.to_crs('3857')
t2n_wo.plot(ax=ax, color='yellow', label='existing network')

gwo.plot(ax=ax, color='red', label='most important projects')

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

fig = plt.figure(figsize=[12,12])
ax = fig.add_axes([0, 0, 1, 1])

t2n_airport_p = t2n_airport_p.to_crs('3857')
t2n_airport_p.plot(ax=ax, color='orange', label='missing connections')

t2n_airport = t2n_airport.to_crs('3857')
t2n_airport.plot(ax=ax, color='yellow', label='existing network')

goa.plot(ax=ax, color='red', label='most important projects')

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

fig = plt.figure(figsize=[12,12])
ax = fig.add_axes([0, 0, 1, 1])

t2n_nimitz_p = t2n_nimitz_p.to_crs('3857')
t2n_nimitz_p.plot(ax=ax, color='orange', label='missing connections')

t2n_nimitz = t2n_nimitz.to_crs('3857')
t2n_nimitz.plot(ax=ax, color='yellow', label='existing network')

gnm.plot(ax=ax, color='red', label='most important projects')

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

t_node = 818
t2n_oak_graph_p.nodes
paths = set()
for node in t2n_oak_graph_p.nodes:
    path = ox.routing.shortest_path(t2n_oak_graph_p, node, t_node)
    if path:
        paths.update(path)

complete = t2n_oak_graph_p.subgraph(paths)
_,g = ox.convert.graph_to_gdfs(complete)
g = g.to_crs('3857')

fig = plt.figure(figsize=[12,12])
ax = fig.add_axes([0, 0, 1, 1])

t2n_airport_p = t2n_airport_p.to_crs('3857')
t2n_airport_p.plot(ax=ax, color='yellow')
g.plot(ax=ax, color='red')

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()



"""# Maps to Display

## schools and buses
"""

import folium
from folium import plugins

# Create the base map with Study Areas
m = final_epcs_gdf.explore(
    color="red",
    style_kwds={
        "fillOpacity": 0.1,
        "weight": 1
    },
    tooltip=True, # Enable tooltip for Study Areas
    popup=True,   # Enable popup for Study Areas
    tiles="CartoDB positron",
    name="Study Areas"
)

# Schools on top
m = final_schools_gdf.explore(
    m=m,
    color="grey",
    name="Schools",
    tooltip=True, # Ensure tooltip is active
    popup=True
)

# Bus stops on top
m = ac_final_stops_gdf.explore(
    m=m,
    color="blue",
    name="Bus Stops",
    tooltip=True, # Ensure tooltip is active
    popup=True
)

# Add a title to the map
title_html = '''
             <h3 align="center" style="font-size:20px"><b>Schools and Bus Stops Map</b></h3>
             '''
m.get_root().html.add_child(folium.Element(title_html))

# Add LayerControl to toggle layers (serves as a legend)
folium.LayerControl().add_to(m)

# Add drawing tools to the map
plugins.Draw().add_to(m)

# Add mouse position display
plugins.MousePosition().add_to(m)

m

# Save the interactive map to an HTML file
m.save("schools_and_buses_map.html")
print("Map saved as schools_and_buses_map.html")

from google.colab import files
files.download('schools_and_buses_map.html')







"""## missing pedestrian connections"""

fig = plt.figure(figsize=[8,8])
ax = fig.add_axes([0, 0, 1, 1])

t2n_wo_only_p = t2n_wo_only_p.to_crs('3857')
t2n_wo_only_p.plot(ax=ax, color='orange', label='missing connections')
t2n_wo_only_p.buffer(5).plot(ax=ax, color='orange', label='missing connections')

t2n_wo = t2n_wo.to_crs('3857')
t2n_wo.plot(ax=ax, color='yellow', label='pedestrian network')

plt.legend()

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

plt.savefig('west_oakland_gaps.png')

fig = plt.figure(figsize=[8,8])
ax = fig.add_axes([0, 0, 1, 1])

t2n_nimitz_only_p = t2n_nimitz_only_p.to_crs('3857')
t2n_nimitz_only_p.plot(ax=ax, color='orange', label='missing connections')
t2n_nimitz_only_p.buffer(10).plot(ax=ax, color='orange', label='missing connections')

t2n_nimitz = t2n_nimitz.to_crs('3857')
t2n_nimitz.plot(ax=ax, color='yellow', label='pedestrian network')

plt.legend()

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

plt.savefig('nimitz_gaps.png')

fig = plt.figure(figsize=[8,8])
ax = fig.add_axes([0, 0, 1, 1])

t2n_airport_only_p = t2n_airport_only_p.to_crs('3857')
t2n_airport_only_p.plot(ax=ax, color='orange', label='missing connections')
t2n_airport_only_p.buffer(5).plot(ax=ax, color='orange', label='missing connections')

t2n_airport = t2n_airport.to_crs('3857')
t2n_airport.plot(ax=ax, color='yellow', label='pedestrian network')

plt.legend()

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

plt.savefig('airport_gaps.png')

"""## New Routes to School"""

wo_routes = get_shortest_routes("West Oakland Middle", wo_sts, t2n_wo_graph)

wo_routes_p = get_shortest_routes("West Oakland Middle", wo_sts, t2n_wo_graph_p)

fig = plt.figure(figsize=[8,8])
ax = fig.add_axes([0, 0, 1, 1])

subgraphs = {k:t2n_wo_graph.subgraph(v) if v else [] for k,v in list(wo_routes.items())}
subgraphs_p = {k:t2n_wo_graph_p.subgraph(v) if v else [] for k,v in wo_routes_p.items()}

wo_schools_gdf.loc[wo_schools_gdf["SchoolName"] == "West Oakland Middle"].plot(ax=ax, color="black", label="school")
wo_stops_gdf.plot(ax=ax, color="orange", label="stops")


t2n_wo_p = t2n_wo_p.to_crs('3857')
t2n_wo_p.plot(ax=ax, color='yellow', label='pedestrian network')

g = gpd.GeoDataFrame()
for k,v in subgraphs_p.items():
    if v:
        _,gdf = ox.convert.graph_to_gdfs(v)
        gdf = gdf.to_crs('3857')
        g = pd.concat([g,gdf])
g.plot(ax=ax, color='red', label='new route')

g = gpd.GeoDataFrame()
for k,v in subgraphs.items():
    if v:
        _,gdf = ox.convert.graph_to_gdfs(v)
        gdf = gdf.to_crs('3857')
        g = pd.concat([g,gdf])
g.plot(ax=ax, color='blue', label='current routes')

plt.legend()

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

plt.savefig('west_oakland_new_routes.png')

sname = "Coliseum College Prep Academy"

oa_routes = get_shortest_routes(sname, oa_sts, t2n_oak_graph)

oa_routes_p = get_shortest_routes(sname, oa_sts, t2n_oak_graph_p)


fig = plt.figure(figsize=[8,8])
ax = fig.add_axes([0, 0, 1, 1])

subgraphs = {k:t2n_oak_graph.subgraph(v) if v else [] for k,v in list(oa_routes.items())}
subgraphs_p = {k:t2n_oak_graph_p.subgraph(v) if v else [] for k,v in oa_routes_p.items()}

oa_schools_gdf.loc[oa_schools_gdf["SchoolName"] == sname].plot(ax=ax, color="black", label="school")
oa_stops_gdf.plot(ax=ax, color="orange", label="stops")


t2n_airport_p = t2n_airport_p.to_crs('3857')
t2n_airport_p.plot(ax=ax, color='yellow', label='pedestrian network')

g = gpd.GeoDataFrame()
for k,v in subgraphs_p.items():
    if v:
        _,gdf = ox.convert.graph_to_gdfs(v)
        gdf = gdf.to_crs('3857')
        g = pd.concat([g,gdf])
g.plot(ax=ax, color='red', label='new route')

g = gpd.GeoDataFrame()
for k,v in subgraphs.items():
    if v:
        _,gdf = ox.convert.graph_to_gdfs(v)
        gdf = gdf.to_crs('3857')
        g = pd.concat([g,gdf])
g.plot(ax=ax, color='blue', label='current routes')

plt.legend()

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

plt.savefig('airport_new_routes.png')

sname = "Downtown Charter Academy"

nm_routes = get_shortest_routes(sname, nm_sts, t2n_nimitz_graph)

nm_routes_p = get_shortest_routes(sname, nm_sts, t2n_nimitz_graph_p)


fig = plt.figure(figsize=[8,8])
ax = fig.add_axes([0, 0, 1, 1])

subgraphs = {k:t2n_nimitz_graph.subgraph(v) if v else [] for k,v in list(nm_routes.items())}
subgraphs_p = {k:t2n_nimitz_graph_p.subgraph(v) if v else [] for k,v in nm_routes_p.items()}

nm_schools_gdf.loc[nm_schools_gdf["SchoolName"] == sname].plot(ax=ax, color="black", label="school")
nm_stops_gdf.plot(ax=ax, color="orange", label="stops")


t2n_nimitz_p = t2n_nimitz_p.to_crs('3857')
t2n_nimitz_p.plot(ax=ax, color='yellow', label='pedestrian network')

g = gpd.GeoDataFrame()
for k,v in subgraphs_p.items():
    if v:
        _,gdf = ox.convert.graph_to_gdfs(v)
        gdf = gdf.to_crs('3857')
        g = pd.concat([g,gdf])
g.plot(ax=ax, color='red', label='new route')

for k,v in subgraphs.items():
    if v:
        _,gdf = ox.convert.graph_to_gdfs(v)
        gdf = gdf.to_crs('3857')
        gdf.plot(ax=ax, color='blue', label='before')

plt.legend()

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

plt.savefig('nimitz_new_routes.png')

"""## Most Important Projects"""

fig = plt.figure(figsize=[8,8])
ax = fig.add_axes([0, 0, 1, 1])

t2n_wo_only_p = t2n_wo_only_p.to_crs('3857')
t2n_wo_only_p.plot(ax=ax, color='orange', label='missing connections')
t2n_wo_only_p.buffer(4).plot(ax=ax, color='orange', label='missing connections')

t2n_wo = t2n_wo.to_crs('3857')
t2n_wo.plot(ax=ax, color='yellow', label='existing network')

gwo.plot(ax=ax, color='red', label='most important projects')
gwo.buffer(7).plot(ax=ax, color='red', label='most important projects')


plt.legend()

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

plt.savefig('west_oakland_important_gap.png')

fig = plt.figure(figsize=[8,8])
ax = fig.add_axes([0, 0, 1, 1])

t2n_airport_only_p = t2n_airport_only_p.to_crs('3857')
t2n_airport_only_p.plot(ax=ax, color='orange', label='missing connections')
t2n_airport_only_p.buffer(5).plot(ax=ax, color='orange', label='missing connections')

t2n_airport = t2n_airport.to_crs('3857')
t2n_airport.plot(ax=ax, color='yellow', label='existing network')

goa.plot(ax=ax, color='red', label='most important projects')
goa.buffer(8).plot(ax=ax, color='red', label='most important projects')

plt.legend()

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

plt.savefig('airport_important_gap.png')

fig = plt.figure(figsize=[8,8])
ax = fig.add_axes([0, 0, 1, 1])

t2n_nimitz_only_p = t2n_nimitz_only_p.to_crs('3857')
t2n_nimitz_only_p.plot(ax=ax, color='orange', label='missing connections')
t2n_nimitz_only_p.buffer(10).plot(ax=ax, color='orange', label='missing connections')

t2n_nimitz = t2n_nimitz.to_crs('3857')
t2n_nimitz.plot(ax=ax, color='yellow', label='existing network')

gnm.plot(ax=ax, color='red', label='most important projects')
gnm.buffer(15).plot(ax=ax, color='red', label='most important projects')

plt.legend()

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

plt.savefig('nimitz_important_gap.png')

"""# End"""

phants = [(route_p[i-1],route_p[i],0) for i in range(1,len(route_p)) if 'phantom' in t2n_wo_graph_p.edges[route_p[i-1],route_p[i],0]['f_type']]
route_p_len = sum([t2n_wo_graph_p.edges[route_p[i-1],route_p[i],0]['length'] for i in range(1,len(route_p))])
route_len = sum([t2n_wo_graph.edges[route[i-1],route[i],0]['length'] for i in range(1,len(route))])

route_p_weight = sum([t2n_wo_graph_p.edges[route_p[i-1],route_p[i],0]['weight'] for i in range(1,len(route_p))])
route_weight = sum([t2n_wo_graph.edges[route[i-1],route[i],0]['weight'] for i in range(1,len(route))])

print(phants)
print(route_p_len)
print(route_len)

print(route_p_weight)
print(route_weight)

# t2n_wo_graph_p.edges[2,3,0]

# get the nearest network nodes to two lat/lng points
orig = ox.distance.nearest_nodes(wo_street_graph, -122.287898, 37.803655) # 7th & Adeline, ID: 2945
dest = ox.distance.nearest_nodes(wo_street_graph, -122.28245, 37.80811) # West Oakland Middle

# find the shortest path between these nodes, minimizing travel time, then plot it
route = ox.routing.shortest_path(wo_street_graph, orig, dest, weight="travel_time_seconds")
fig, ax = ox.plot.plot_graph_route(wo_street_graph, route, node_size=5)

"""## **4. Export Files**"""

# Export raw data files for Github Repository
oak_hin_ped.to_file("2024 Oakland Pedestrian High Injury Network", driver="GeoJSON")
oak_speed_limits.to_file("Oakland Speed Limits", driver="GeoJSON")
ac_transit_stops.to_file("AC Transit Stops", driver="GeoJSON")

"""# ***Anwar's Stuff***"""

t2n_wo_osmnx = ox.project_graph(t2n_graphs['West Oakland'])
t2n_wo_osmnx = ox.distance.add_edge_lengths(t2n_wo_osmnx)
t2n_wo_osmnx = ox.convert.to_undirected(t2n_wo_osmnx)

t2n_oa_osmnx = ox.project_graph(t2n_graphs['Airport'])
t2n_oa_osmnx = ox.distance.add_edge_lengths(t2n_oa_osmnx)
# t2n_oa_osmnx = ox.convert.to_undirected(t2n_oa_osmnx)

fig, ax = ox.plot_graph(t2n_wo_osmnx, show=False, close=False)

t = t2n_wo_osmnx
# t = t2n_graphs['West Oakland']
wog = street_graphs['West Oakland']
sp = nx.shortest_path(wog, source=53079193, target=13207152948)

c2n = {tuple(t.nodes[x].values()):x for x in t.nodes}
print(len(t.edges))
t.edges

path = nx.shortest_path(t,source=300,target=20)
path

fig, ax = ox.plot_graph(wog.subgraph(sp), show=False, close=False)
fig, ax = ox.plot_graph(wog, show=False, close=False)

gdf_nodes, gdf_edges = ox.convert.graph_to_gdfs(t)
gt = gdf_edges

gdf_nodes, gdf_edges = ox.convert.graph_to_gdfs(t.subgraph([301,300]))
gp = gdf_edges

gdf_nodes, gdf_edges = ox.convert.graph_to_gdfs(t.subgraph(path))
gp2 = gdf_edges

gdf_nodes, gdf_edges = ox.convert.graph_to_gdfs(wog.subgraph(sp))
gp3 = gdf_edges

gdf_nodes, gdf_edges = ox.convert.graph_to_gdfs(wog)
gpg = gdf_edges

fig = plt.figure(figsize=[12,12])
ax = fig.add_axes([0, 0, 1, 1])

t2n_wo = t2n_wo.to_crs(3857)
t2n_wo.plot(ax=ax, color='blue', label='sidewalks')

gpg = gpg.to_crs(3857)
gpg.plot(ax=ax, color='yellow', label = 'street')

gp3 = gp3.to_crs(3857)
gp3.plot(ax=ax, color='red', label = 'path')



# gp2 = gp2.to_crs(3857)
# gp2.buffer(10,cap_style="flat").plot(ax=ax, color='red', label = 'path')

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

l = gp2.loc[(gp2['from'] == 250) & (gp2['to'] == 258)].iloc[0].geometry

l.length

"""# time for the main course, gap closure algorithm time!"""

def fill_sidewalk_gaps_along_path(path, # list of nodes in the path, e.g. [20,21,24,33,50]
                                  street_graph,
                                  sidewalk_graph):
    '''
    runs along the path and checks on either side for sidewalks, notes where there are gaps and adds "phantom edges"
    '''
    # index along path
    i = 1
    while i < len(path):
        u = path[i-1] # from
        v = path[i] # to
        # get the linestring for this path segment
        line = street_graph.loc[(street_graph['from'] == u) & (street_graph['to'] == v)].iloc[0].geometry
        # get the direction of this line, as an angle between 0 and 360
        direction = get_direction(line)
        # these are how we iterate over this line
        distance = 0
        current_point = Point([0,0])
        current_edge1 = None
        current_edge2 = None
        # paramaters to play with regarding searching
        search_width = 3 # currently arbitrarily set, determines how frequently we check for sidewalks, smaller number means more frequent
        search_dist = 15 # currently arbitrarily set, determines how far to look for a sidewalk
        gap_close_width = 15 # currently arbitrarily set, determine how generous of an angle to look for a connecting sidewalk and street
        gap_close_dist = 30 # currently arbitrarily set, determine how long of a gap we are willing to close
        while distance < line.length:
            # create a point along the line as the origin for the sidewalk search
            distance += search_width
            current_point = line.interpolate(distance)
            # set the two directions to search, perpendicular to this line's direction
            search_d1 = (direction + 90) % 360
            search_d2 = (direction - 90) % 360
            search_box1 = draw_line(current_point, search_d1, search_dist).buffer(search_width, cap_style="flat")
            search_box2 = draw_line(current_point, search_d2, search_dist).buffer(search_width, cap_style="flat")
            # look for sidewalk edges in the search boxes
            sb1df = gpd.GeoDataFrame(geometry=[search_box1],crs="3857") # set up the space for a spatial join
            sb2df = gpd.GeoDataFrame(geometry=[search_box2],crs="3857")
            found_edges1 = sb1df.sjoin(sidewalk_graph, how="inner")
            found_edges2 = sb2df.sjoin(sidewalk_graph, how="inner")
            # time to handle sidewalk cases
            current_edge1, new_edges1 = handle_edge_cases(found_edges1,current_edge1)
            current_edge2, new_edges2 = handle_edge_cases(found_edges2,current_edge2)
            for edge in new_edges1:
                add_edge()



def handle_edge_cases(found_edges, current_edge):
    '''
    returns (new current edge, [new edges to create])

    if the lines we are searching on are generally straight, then before we set a new edge,
    we need to make sure it's direction isn't drastically different from the old edge,
    to catch turns we don't want to take

    handles the following cases:

    if there is no found edge:
        if there is no current edge, do nothing
        elif there is a current edge:
            the current edge must have ended in the previous window, time to do a search for a gap to close!
    if there is only one found edge:
        if there is no current edge, then this is your new current edge
        elif this edge matches your current edge, do nothing
        else
            so long as the search areas dont leave gaps, im not sure when this would happen
    if there are two found edges:
        if there is no current edge:
            ummmm pick the edge further in your current direction and set that to current edge??
        if neither of the found edges is the current edge:
            if the two are connected to each other, make a new edge from the current edge to the closer one of the two, and set the current edge to the further of the two
            if they aren't connected...gross...try to connect them too??
        if the two are connected ("to" of one matches "from" of the second)
            set a new current edge to the other found edge

    '''
    if len(found_edges) == 0:
        if not current_edge:
            return (current_edge, [])
        elif current_edge:
            # TODO search time!
            new_edge = None # search function call
            # TODO check direction first
            return (new_edge, [new_edge])
    if len(found_edges) == 1:
        found_edge = (int(found_edges.iloc[0]['from']), int(found_edges.iloc[0]['to']))
        if not current_edge:
            return (found_edge, [])
        elif found_edge == current_edge:
            return (current_edge, [])
        else:
            print('only one edge thats different from current edge? investigate...')
    if len(found_edges == 2):
        if not current_edge:
            # figure out which edge is further along...if the direction doesn't change too much between the two
            further_edge = found_edges[1]
            # TODO check direction of further edge
            return (further_edge, [])
        if current_edge not in found_edges:
            # TODO gross, later
           other_edge = [x for x in found_edges if x != current_edge][0]
        # TODO check direction of new edge, doesn't stop drawing new edges, but determines which edge to set as current_edge
        if current_edge[1] == other_edge[0]:
            return (other_edge,[])
        else:
            new_edge = (current_edge[1], other_edge[0])
            # if direction of other edge isn't very different:
            return (other_edge, [new_edge])
            # else return (new_edge, [new_edge])
    if len(found_edges > 2):
        # gross gross gross


def add_edge(edges_df, node_df, new_edge):
    '''
    edges_df has following columns: index(u,v,key=0), f_type, length, from, to, geometry
    new_edge is a tuple of two node ids
    '''
    return

a.interpolate(.2).coords[:]

# path

"""# More helper functions"""

def get_direction(line):
    p0, p1 = line.coords[:][0], line.coords[:][-1]
    dx = p1[0] - p0[0]
    dy = p1[1] - p0[1]
    rads = math.atan2(dy, dx)
    # Convert to degrees
    degrees = math.degrees(rads)
    # Optional: Normalize to [0, 360)
    return degrees if degrees >= 0 else degrees + 360

def draw_line(point, angle_deg, distance):
    # Convert angle to radians
    angle_rad = math.radians(angle_deg)
    # Calculate end point coordinates
    x1, y1 = point.coords[:][0]
    x2 = x1 + distance * math.cos(angle_rad)
    y2 = y1 + distance * math.sin(angle_rad)
    # Create and return line
    return LineString([point, Point([x2, y2])])

from shapely import LineString, Point
a = LineString([[1,3**.5],[0,0]])
p = Point([2,3])

print(get_direction(a))
b = draw_line(p, 0, 1)
print(b.coords[:])
b

b.buffer(.2,cap_style="flat",)

sp = nx.shortest_path(wog, source=13207152938, target=53090368)

sp

gp3

line = gp3.loc[(53090368, 53030319,0)].geometry
line

pp = line.interpolate(50)

direction = get_direction(line)
# these are how we iterate over this line
# distance = 0
# current_point = Point([0,0])
# current_edge1 = None
# current_edge2 = None
# paramaters to play with regarding searching
search_width = 3 # currently arbitrarily set, determines how frequently we check for sidewalks, smaller number means more frequent
search_dist = 10 # currently arbitrarily set, determines how far to look for a sidewalk
gap_close_width = 10 # currently arbitrarily set, determine how generous of an angle to look for a connecting sidewalk and street
gap_close_dist = 20 # currently arbitrarily set, determine how long of a gap we are willing to close
# create a point along the line as the origin for the sidewalk search
# distance += search_width
# current_point = line.interpolate(distance)
# set the two directions to search, perpendicular to this line's direction
search_d1 = (direction + 90) % 360
search_d2 = (direction - 90) % 360
search_box1 = draw_line(pp, search_d1, search_dist).buffer(search_width, cap_style="flat")
search_box2 = draw_line(pp, search_d2, search_dist).buffer(search_width, cap_style="flat")

fig = plt.figure(figsize=[8,8])
ax = fig.add_axes([0, 0, 1, 1])

g = gpd.GeoDataFrame(geometry=[line, pp,search_box1],crs=3857)
g.plot(ax=ax, color="orange")


ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

search_box1 = draw_line(pp, search_d1, search_dist).buffer(search_width, cap_style="flat")
search_box1

gj = gpd.GeoDataFrame(geometry=[search_box1],crs=3857)
gt = gt.to_crs(3857)
found_edges = gj.sjoin(gt,how="inner")
(int(found_edges.iloc[0]['from']), int(found_edges.iloc[0]['to']))

test_street = LineString([[0,5], [100,5]])
test_sidewalk1, test_sidewalk2 = LineString([[0,8],[60,8]]), LineString([[70,8],[100,8]])
test_street_df = gpd.GeoDataFrame(geometry=[test_street],crs="3857")
test_sidewalk_df = gpd.GeoDataFrame(geometry=[test_sidewalk1,test_sidewalk2],crs="3857")
t_street_g = gdf_to_graph(test_street_df)
t_sidewalk_g = gdf_to_graph(test_sidewalk_df)
t_street_g = ox.convert.to_undirected(t_street_g)
t_sidewalk_g = ox.convert.to_undirected(t_sidewalk_g)

_, t_street_df = ox.convert.graph_to_gdfs(t_street_g)
_, t_sidewalk_df = ox.convert.graph_to_gdfs(t_sidewalk_g)

fig = plt.figure(figsize=[8,8])
ax = fig.add_axes([0, 0, 1, 1])

t_street_df.plot(ax=ax, color="orange")
t_sidewalk_df.plot(ax=ax, color="blue")

ax.set_axis_off()

t_sidewalk_df

# t_sidewalk_df[(1,2,0)] = {"geometry":LineString([[60,8],[70,8]])}
idx = pd.MultiIndex.from_product([[1],[2],[0]],
                                 names=['u', 'v','key'])

new_edge = gpd.GeoDataFrame(index=idx,geometry=[LineString([[60,8],[70,8]])],crs="4326")
t_sidewalk_df = pd.concat([t_sidewalk_df,new_edge])
t_sidewalk_df

gt.head()



"""## **TRASH CAN**"""

# Create an empty list
results = []

# Organize a for loop of the distance columns to sort values
for col in distance_cols:

    temp = (
        ac_final_stops_gdf
        .sort_values(col)
        .drop_duplicates(subset="ROUTE") # Drop items with the same route after sorting columns
        .head(3) # Save the first three items
        .copy()
    )

    temp["school_distance_col"] = col # create the list

    results.append(temp)

closest_stops_df = pd.concat(results, ignore_index=True) # Organize into a dataframe

ac_final_stops_gdf.sort_values(by='dist_to_Downtown_Charter_Academy', ascending=True)[["dist_to_Downtown_Charter_Academy","geoid", "STP_511_ID",
                                                                                       "STP_DESCRI", "ROUTE"]].head(5)

closest_stops_df.groupby("geoid")[
    ["STP_511_ID", "STP_DESCRI", "ROUTE", "school_distance_col"]
].value_counts()

t2n_wo_osmnx = ox.add_edge_speeds(t2n_wo_osmnx , fallback=5)  # Set travel speed to 5 km/hr
t2n_wo_osmnx = ox.add_edge_travel_times(t2n_wo_osmnx)

# t2n_oa_osmnx = ox.project_graph(t2n_graphs['Oakland Airport'])
# t2n_oa_osmnx = ox.distance_add_edge_lengths(t2n_oa_osmnx)
# t2n_oa_osmnx = ox.add_edge_speeds(t2n_oa_osmnx, fallback=5)
# t2n_oa_osmnx = ox.add_edge_travel_times(t2n_oa_osmnx)

# get the nearest network nodes to two lat/lng points
orig = ox.distance.nearest_nodes(G, -122.245846, 37.828903)
dest = ox.distance.nearest_nodes(G, -122.215006, 37.812303)

# find the shortest path between these nodes, minimizing travel time, then plot it
route = ox.routing.shortest_path(t2n_wo_osmnx, orig, dest, weight="travel_time")
fig, ax = ox.plot.plot_graph_route(t2n_wo_osmnx, route, node_size=0)

def gdf_to_graph(edges_gdf):

    # IMPORTANT: use MultiDiGraph for OSMnx compatibility
    G = nx.MultiDiGraph()

    node_id_map = {}
    node_counter = 0

    def get_node_id(coord):
        nonlocal node_counter

        if coord not in node_id_map:
            node_id_map[coord] = node_counter
            G.add_node(
                node_counter,
                x=coord[0],
                y=coord[1]
            )
            node_counter += 1

        return node_id_map[coord]

    for _, row in edges_gdf.iterrows():

        geom = row.geometry
        if geom is None or geom.is_empty:
            continue

        # Normalize geometry types
        if geom.geom_type == "LineString":
            lines = [geom]

        elif geom.geom_type == "MultiLineString":
            lines = list(geom.geoms)

        else:
            continue

        # Clean attributes (OSMnx-safe: no lists/dicts)
        attr = row.drop("geometry").to_dict()
        attr = {k: str(v) if isinstance(v, (list, dict)) else v for k, v in attr.items()}

        for line in lines:

            coords = list(line.coords)
            if len(coords) < 2:
                continue

            u = get_node_id(coords[0])
            v = get_node_id(coords[-1])

            G.add_edge(u, v, **attr)

    # --- CRITICAL: OSMnx metadata fixes ---
    G.graph["crs"] = "EPSG:4326"
    G.graph["simplified"] = True

    return G

G = gdf_to_graph(t2n_nimitz)

fig, ax = ox.plot_graph(G)

def plot_interactive_map(G):

    # Convert graph → GeoDataFrames
    nodes, edges = ox.graph_to_gdfs(G)

    # Ensure edges are in lat/lon
    edges = edges.to_crs(epsg=4326)

    # Compute map center (IMPORTANT FIX)
    center = [
        edges.geometry.centroid.y.mean(),
        edges.geometry.centroid.x.mean()
    ]

    # Create map
    m = folium.Map(location=center, zoom_start=13, tiles="CartoDB positron")

    # --- Road network ---
    folium.GeoJson(
        edges,
        style_function=lambda x: {
            "color": "#5DADE2",
            "weight": 2,
            "opacity": 0.6
        },
        name="Road Network"
    ).add_to(m)

      # --- Nodes ---
    for _, row in nodes.iterrows():
            folium.CircleMarker(
                location=[row.geometry.y, row.geometry.x],
                radius=1.5,
                color="black",
                fill=True,
                fill_opacity=0.7
            ).add_to(m)

    folium.LayerControl().add_to(m)

    # Layer control
    folium.LayerControl().add_to(m)

    return m

plot_interactive_map(G)

def gdf_to_graph(edges_gdf):

    G = nx.Graph()

    for _, row in edges_gdf.iterrows():

        geom = row.geometry

        # handle LineString only (skip invalids safely)
        if geom is None:
            continue

        if geom.geom_type == "LineString":

            coords = list(geom.coords)

            u = coords[0]
            v = coords[-1]

            # add nodes with attributes
            G.add_node(u, x=u[0], y=u[1])
            G.add_node(v, x=v[0], y=v[1])

            # add edge attributes safely
            attr = row.drop("geometry").to_dict()
            G.add_edge(u, v, **attr)

        # If the geometry is a MultiLineString:
        elif geom.geom_type == "MultiLineString":

            for line in geom.geoms:
                coords = list(line.coords)

                u = coords[0]
                v = coords[-1]

                G.add_node(u, x=u[0], y=u[1])
                G.add_node(v, x=v[0], y=v[1])

                attr = row.drop("geometry").to_dict()
                G.add_edge(u, v, **attr)

    return G

G = gdf_to_graph(t2n_wo)
G.graph["crs"] = "EPSG:4326"
G.graph["simplified"] = True
G = nx.MultiDiGraph(G)

G

u, v, data = list(G.edges(data=True))[0]
print(data)

fig, ax = ox.plot_graph(G)

gdf_nodes, gdf_edges = ox.convert.graph_to_gdfs(t2n_oak_graph)
ga = gdf_edges

gdf_nodes, gdf_edges = ox.convert.graph_to_gdfs(t2n_oak_graph_p)
gap = gdf_edges

fig = plt.figure(figsize=[12,12])
ax = fig.add_axes([0, 0, 1, 1])

gap = gap.to_crs(3857)
gap.plot(ax=ax, color='red', label = 'withPhantom')

ga = ga.to_crs(3857)
ga.plot(ax=ax, color='blue', label='sidewalks')

# gp3 = gp3.to_crs(3857)
# gp3.plot(ax=ax, color='red', label = 'path')



# gp2 = gp2.to_crs(3857)
# gp2.buffer(10,cap_style="flat").plot(ax=ax, color='red', label = 'path')

ctx.add_basemap(ax, source=ctx.providers.CartoDB.Positron)
ax.set_axis_off()

