# -*- coding: utf-8 -*-
"""functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lH0UfvraejGYvpjFmhyHQBPujkNuCE7M

# I. Github Upload Functions

## 1. *gdf* --> github upload
"""

## gdf --> github upload
def upload_gdf_to_github(gdf, filename, target_folder='data/processed'):
    """
    Saves a GeoDataFrame as a GeoJSON and pushes it to the MAPN github repository.
    """
    import os

    # setup
    TOKEN = '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'  # add your token here, this one is NF's
    OWNER = 'AnwarBaroudi'
    REPO = 'MAPN'
    BRANCH = 'main'
    REPO_URL = f"https://{TOKEN}@github.com/{OWNER}/{REPO}.git"

    #saves locally to colab
    gdf.to_file(filename, driver="GeoJSON")
    print(f" saved {filename} locally")

    #clones
    if os.path.exists(REPO):
        !rm -rf {REPO}

    !git clone {REPO_URL}

    if os.path.exists(REPO):
        # git user info (NF)
        !git config --global user.email "noelani@berkeley.edu"
        !git config --global user.name "noelanifix"
        !mkdir -p {REPO}/{target_folder}
        !cp {filename} {REPO}/{target_folder}/

        #push to git
        !cd {REPO} && git add {target_folder}/{filename} && git commit -m "update {filename}" && git push {REPO_URL} {BRANCH}

        print(f"success: {filename} now in {REPO}/{target_folder}")
    else:
        print("failed")

#how to use function:
# upload_gdf_to_github(proj_schools_public_gdf, "proj_schools_public.geojson")
# upload_gdf_to_github(another_gdf, "another_file_name.geojson")

"""## 2. large files: drive --> github upload

"""

## large files: drive --> github upload
import os
import shutil
from google.colab import drive
drive.mount('/content/drive')

def upload_large_file_to_github_lfs(filepath, target_folder='data/processed',
                                     email='noelani@berkeley.edu', name='noelanifix'):
    """
    Uploads any large file to GitHub via LFS.

    Args:
        filepath     : full path to the file (handles spaces)
        target_folder: folder in the repo to upload to (default: 'data/processed')
        email        : git config email
        name         : git config username

    Example usage:
        upload_large_file_to_github_lfs('/content/drive/MyDrive/somefolder/bigfile.zip')
        upload_large_file_to_github_lfs('/content/drive/MyDrive/somefolder/bigfile.shp', target_folder='data/raw')
    """
    TOKEN = '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'
    OWNER = 'AnwarBaroudi'
    REPO  = 'MAPN'
    BRANCH = 'main'
    REPO_URL = f"https://{TOKEN}@github.com/{OWNER}/{REPO}.git"
    filename = os.path.basename(filepath)
    ext = os.path.splitext(filename)[1]  # e.g. .zip, .shp, .geojson

    # Verify file exists
    if not os.path.exists(filepath):
        print(f"ERROR: File not found: {filepath}")
        print("Files in that directory:")
        for f in os.listdir(os.path.dirname(filepath)):
            print(f"  {f}")
        return

    print(f"found: {filename} ({os.path.getsize(filepath) / 1e6:.1f} MB)")

    !apt-get install -y git-lfs -q

    if os.path.exists(REPO):
        !rm -rf {REPO}
    !git clone {REPO_URL}

    if not os.path.exists(REPO):
        print("clone failed")
        return

    !git config --global user.email "{email}"
    !git config --global user.name "{name}"

    # Initialize LFS and track the file type
    !cd {REPO} && git lfs install
    !cd {REPO} && git lfs track "*{ext}"
    !cd {REPO} && git add .gitattributes

    # Copy file using Python (handles spaces in paths)
    dest = f"{REPO}/{target_folder}"
    os.makedirs(dest, exist_ok=True)
    shutil.copy2(filepath, os.path.join(dest, filename))
    print(f"copied {filename} → {dest}")

    # Commit and push
    !cd {REPO} && git add {target_folder}/{filename}
    !cd {REPO} && git commit -m "add {filename} via LFS"
    !cd {REPO} && git push {REPO_URL} {BRANCH}

    print(f"successful upload: {filename} → {OWNER}/{REPO}/{target_folder}")


#to use:

# Zip file
# upload_large_file_to_github_lfs('/content/drive/MyDrive/MCP/255 - Urban Informatics/final/alameda_footprints.zip')

# Shapefile
# upload_large_file_to_github_lfs('/content/drive/MyDrive/somefolder/myfile.shp', target_folder='data/raw')

# GeoJSON
# upload_large_file_to_github_lfs('/content/drive/MyDrive/somefolder/myfile.geojson', target_folder='data/processed')

"""## 3. upload PNG --> github via API


"""

import os, base64, requests

def upload_png_to_github(filepath, target_folder='outputs/visuals'):
    """
    Uploads a PNG (or any file under ~50MB) to the MAPN GitHub repo.
    Handles both create and update — no git clone needed.

    Args:
        filepath      : local path to the file
        target_folder : repo folder to upload into (default 'outputs/visuals')

    Example:
        upload_png_to_github('alameda_zvhhs_tracts_pct_zvhhs_bxplot.png')
        upload_png_to_github('my_chart.png', target_folder='outputs/schools')
    """
    TOKEN  = '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'
    OWNER  = 'AnwarBaroudi'
    REPO   = 'MAPN'
    BRANCH = 'main'

    filename  = os.path.basename(filepath)
    repo_path = f'{target_folder}/{filename}'
    url       = f'https://api.github.com/repos/{OWNER}/{REPO}/contents/{repo_path}'
    headers   = {'Authorization': f'token {TOKEN}'}

    with open(filepath, 'rb') as f:
        content = base64.b64encode(f.read()).decode('utf-8')

    response = requests.get(url, headers=headers)
    sha = response.json().get('sha') if response.status_code == 200 else None

    payload = {'message': f'update {filename}', 'content': content, 'branch': BRANCH}
    if sha:
        payload['sha'] = sha

    result = requests.put(url, headers=headers, json=payload)
    if result.status_code in [200, 201]:
        print(f'uploaded: {filename} → {repo_path}')
    else:
        print(f'failed:   {filename} — {result.json().get("message")}')

#how to use function:
# upload_png_to_github(filepath, target_folder='outputs/visuals')

"""# II. Analysis Functions"""

# MTC brand colors
mtc_colors = {
    'Equity Priority Community':     '#fb2739',
    'Non-Equity Priority Community': '#285b8e'
}

"""## 3. plot: distribution + 95% CI"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.ticker import FormatStrFormatter

mtc_colors = {
    'Equity Priority Community':     '#fb2739',
    'Non-Equity Priority Community': '#285b8e'
}

def plot_distribution_and_mean_ci(
    df, y_col, x_col, title_prefix, x_label,
    y_label_boxplot, y_label_pointplot, filename_prefix,
    palette, ylim_multiplier=1.1
):
    """
    Saves a boxplot and a 95% CI point plot for any numeric column
    split by a categorical column. Returns list of saved filenames.

    Args:
        df               : DataFrame
        y_col            : numeric column to plot (e.g. 'pct_zvhhs')
        x_col            : categorical column to split by (e.g. 'type')
        title_prefix     : shown in chart titles
        x_label          : x-axis label
        y_label_boxplot  : y-axis label for boxplot
        y_label_pointplot: y-axis label for CI plot
        filename_prefix  : prefix for saved .png filenames
        palette          : dict mapping category → color
        ylim_multiplier  : headroom above max value (default 1.1)

    Example:
        plot_distribution_and_mean_ci(
            df=ac_zvhhs, y_col='pct_zvhhs', x_col='type',
            title_prefix='Zero Vehicle Households',
            x_label='Tract Type',
            y_label_boxplot='Proportion Without a Vehicle',
            y_label_pointplot='Proportion ZVH',
            filename_prefix='alameda_zvhhs',
            palette=mtc_colors
        )
    """
    generated_files = []
    df_clean = df.copy()
    df_clean[y_col] = pd.to_numeric(df_clean[y_col], errors='coerce')
    df_clean = df_clean.dropna(subset=[y_col, x_col])

    # Box plot
    fig_bx, ax_bx = plt.subplots(figsize=(10, 6))
    sns.boxplot(x=x_col, y=y_col, data=df_clean,
                hue=x_col, palette=palette, legend=False, ax=ax_bx)
    ax_bx.set_title(f'Distribution of {title_prefix}\nIn Alameda County Census Tracts')
    ax_bx.set_xlabel(x_label)
    ax_bx.set_ylabel(y_label_boxplot)
    ax_bx.set_ylim(0, df_clean[y_col].max() * ylim_multiplier)
    ax_bx.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    bx_filename = f'{filename_prefix}_{y_col}_bxplot.png'
    plt.savefig(bx_filename, dpi=300, bbox_inches='tight', facecolor='white')
    plt.close(fig_bx)
    generated_files.append(bx_filename)

    # Point plot (mean + 95% CI)
    fig_pt, ax_pt = plt.subplots(figsize=(6, 4))
    sns.pointplot(data=df_clean, x=x_col, y=y_col, hue=x_col,
                  errorbar=('ci', 95), linestyle='none', capsize=0.2,
                  palette=palette, legend=False, ax=ax_pt)
    ax_pt.yaxis.set_major_formatter(FormatStrFormatter('%.2f'))
    ax_pt.set_ylabel(y_label_pointplot)
    ax_pt.set_xlabel(x_label)
    ax_pt.set_title(f'Average Share of {title_prefix}\nBy {x_label} with 95% CI')
    plt.tight_layout()
    pt_filename = f'{filename_prefix}_{y_col}_95CI.png'
    plt.savefig(pt_filename, dpi=300, bbox_inches='tight', facecolor='white')
    plt.close(fig_pt)
    generated_files.append(pt_filename)

    return generated_files